# CNN 모델로 창포(Iris) 분류하기


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import optimizers
# from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dense, Conv1D, Flatten

In [ ]:
!wget https://raw.githubusercontent.com/dhrim/cau_2021/master/material/deep_learning/iris_with_category_index.csv
  

--2022-08-08 12:04:37--  https://raw.githubusercontent.com/dhrim/cau_2021/master/material/deep_learning/iris_with_category_index.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2218 (2.2K) [text/plain]
Saving to: ‘iris_with_category_index.csv’

iris_with_category_ 100%[===================>]   2.17K  --.-KB/s    in 0s      

2022-08-08 12:04:37 (33.6 MB/s) - ‘iris_with_category_index.csv’ saved [2218/2218]



In [ ]:
iris = pd.read_csv("iris_with_category_index.csv")
iris.head(10)

septal_length  septal_width  petal_length  petal_width  class
0            6.4           2.8           5.6          2.2      2
1            5.0           2.3           3.3          1.0      1
2            4.9           2.5           4.5          1.7      2
3            4.9           3.1           1.5          0.1      0
4            5.7           3.8           1.7          0.3      0
5            4.4           3.2           1.3          0.2      0
6            5.4           3.4           1.5          0.4      0
7            6.9           3.1           5.1          2.3      2
8            6.7           3.1           4.4          1.4      1
9            5.1           3.7           1.5          0.4      0

In [ ]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 5)
[[6.4 2.8 5.6 2.2 2. ]
 [5.  2.3 3.3 1.  1. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.7 3.8 1.7 0.3 0. ]]


In [ ]:
x = data[:,:4]
y = data[:,4:]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

train_x = np.reshape(train_x, (100, 4, 1))  # ADD
test_x = np.reshape(test_x, (20, 4, 1))     # ADD

print(train_x.shape)  # ADD
print(test_x.shape)   # ADD


(100, 4)
(100, 1)
(20, 4)
(20, 1)
(100, 4, 1)
(20, 4, 1)


In [ ]:
model = keras.Sequential()
model.add(Conv1D(4, 3, activation='relu', input_shape=(4,1))) # ADD
model.add(Flatten())  # ADD
# model.add(Dense(10, activation='relu', input_shape=(4,)))
model.add(Dense(10, activation='relu')) # modify
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation="softmax")) # 1이 아니고 클래스 수 3이다

model.compile(optimizer="SGD", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.summary()

model.fit(train_x, train_y, epochs=1000, verbose=0, batch_size=20)

loss, acc = model.evaluate(test_x, test_y)
print("loss=", loss)
print("acc=", acc)


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 2, 4)              16        
                                                                 
 flatten (Flatten)           (None, 8)                 0         
                                                                 
 dense (Dense)               (None, 10)                90        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 3)                 33        
                                                                 
Total params: 249
Trainable params: 249
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 149ms/step - los

In [ ]:
y_ = model.predict(test_x)
print(y_)
print(np.argmax(y_, axis=1))

[[9.9481457e-01 5.1853964e-03 6.3893681e-27]
 [1.7705390e-02 9.8229194e-01 2.6848616e-06]
 [9.3543452e-01 6.4565539e-02 1.8461817e-21]
 [1.6085086e-02 9.8390895e-01 5.9929484e-06]
 [9.9433929e-01 5.6607514e-03 1.8071182e-26]
 [9.9872774e-01 1.2722549e-03 3.5791745e-30]
 [9.9931896e-01 6.8101013e-04 1.8292077e-31]
 [9.9901140e-01 9.8860916e-04 1.7827111e-30]
 [2.5023811e-02 9.7497571e-01 4.4836790e-07]
 [9.9251336e-01 7.4865911e-03 9.5537108e-26]
 [1.6197738e-04 1.3307020e-01 8.6676776e-01]
 [6.0086953e-03 9.9355316e-01 4.3812496e-04]
 [9.9253464e-01 7.4653197e-03 5.6668600e-26]
 [1.6241184e-04 1.3197741e-01 8.6786020e-01]
 [9.9081403e-01 9.1859214e-03 2.2247455e-25]
 [2.2088108e-03 9.3729138e-01 6.0499746e-02]
 [1.0690789e-02 9.8924899e-01 6.0295763e-05]
 [9.8732853e-01 1.2671445e-02 1.6713908e-24]
 [9.9592626e-01 4.0737502e-03 2.3628765e-27]
 [1.4654065e-02 9.8534101e-01 4.8764587e-06]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 1]
